-- public.workspaces definition

CREATE TABLE public.workspaces (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	created_by uuid NULL,
	join_code varchar NULL,
	CONSTRAINT workspaces_pkey PRIMARY KEY (id)
);


-- public.workspaces foreign keys

ALTER TABLE public.workspaces ADD CONSTRAINT workspaces_workspace_user_id_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);

-- public.workspace_members definition

CREATE TABLE public.workspace_members (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id uuid DEFAULT gen_random_uuid() NOT NULL,
	workspace_id uuid DEFAULT gen_random_uuid() NOT NULL,
	"role" varchar DEFAULT 'member'::character varying NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT workspace_members_pkey PRIMARY KEY (id, user_id)
);


-- public.workspace_members foreign keys

ALTER TABLE public.workspace_members ADD CONSTRAINT members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
ALTER TABLE public.workspace_members ADD CONSTRAINT members_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id);


-- public.messages definition

CREATE TABLE public.messages (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	channel_id uuid NULL,
	user_id uuid NULL,
	"content" jsonb NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	is_edited bool DEFAULT false NULL,
	CONSTRAINT messages_pkey PRIMARY KEY (id)
);


-- public.messages foreign keys

ALTER TABLE public.messages ADD CONSTRAINT messages_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.channels(id);
ALTER TABLE public.messages ADD CONSTRAINT messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);

-- public.channels definition
CREATE TABLE public.channels (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	workspace_id uuid NOT NULL,
	is_public bool DEFAULT true NOT NULL,
	CONSTRAINT channels_id_key UNIQUE (id),
	CONSTRAINT channels_pkey PRIMARY KEY (id)
);


-- public.channels foreign keys

ALTER TABLE public.channels ADD CONSTRAINT channels_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id);

